task:
  name: freebsd
  freebsd_instance:
    image: freebsd-13-2-release-amd64
  setup_rust_script:
    - pkg install -y git bash binutils
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh --default-toolchain none -y --profile=minimal
  target_cache:
    folder: build/cg_clif
  prepare_script:
    - . $HOME/.cargo/env
    - ./y.sh prepare
  test_script:
    - . $HOME/.cargo/env
    - ./y.sh test

task:
  name: macOS (AArch64)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  setup_rust_script:
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh --default-toolchain none -y --profile=minimal
  target_cache:
    folder: build/cg_clif
  prepare_script:
    - uname -a
    - . $HOME/.cargo/env
    - ./y.sh prepare
  test_script:
    - . $HOME/.cargo/env
    - ./y.sh test
